// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TranslatorApp.DataAccessLayer.TranslatorDbContext;

#nullable disable

namespace TranslatorApp.Migrations
{
    [DbContext(typeof(TranslateDbContext))]
    [Migration("20231120131256_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TranslatorApp.Entities.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WordId"));

                    b.Property<string>("Azerbaycan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Latin")
                        .HasColumnType("text");

                    b.Property<string>("Ozbek")
                        .HasColumnType("text");

                    b.Property<string>("Qazax")
                        .HasColumnType("text");

                    b.Property<string>("Rus")
                        .HasColumnType("text");

                    b.Property<string>("Turk")
                        .HasColumnType("text");

                    b.Property<string>("UnSelected")
                        .HasColumnType("text");

                    b.HasKey("WordId");

                    b.HasIndex("Azerbaycan")
                        .IsUnique();

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
